/* Shared device library; reads existing tool libraries without copying or deleting them. */
(function(root){
 const keys={'routine':'routineVisualTimer.savedRoutines','chore-chart':'routineVisualTimer.savedChoreCharts.v1','token-board':'routineVisualTimer.tokenBoards.v2','homework-planner':'routineVisualTimer.homework.v1','self-monitor':'routineVisualTimer.selfMonitor.v1'};
 for(const type of ['first-then','choice-board','task-strip','now-next-later','calm-down'])keys[type]=`routineVisualTimer.visualSupports.${type}.v1`;
 const type=p=>p.format==='routine-visual-timer'?'routine':p.format==='weekly-chore-chart'?'chore-chart':p.board?.type||p.format;
 const title=p=>p.routine?.name??p.chart?.name??p.board?.title??'Untitled board';
 function rename(p,name){if(!name.trim()||name.length>100)throw Error('Use a board name between 1 and 100 characters.');p=JSON.parse(JSON.stringify(p));if(p.routine)p.routine.name=name.trim();else if(p.chart)p.chart.name=name.trim();else p.board.title=name.trim();return p;}
 function path(p){const t=type(p);if(!keys[t])throw Error('Unknown visual type.');return t==='routine'?'':t+'/';}
 function list(storage){const all=[];for(const [t,key] of Object.entries(keys)){const items=JSON.parse(storage.getItem(key)||'[]');if(!Array.isArray(items))throw Error('A device library could not be read. Export your open board before making changes.');for(const item of items){if(!item||typeof item.id!=='string')continue;const payload=t==='routine'?{format:'routine-visual-timer',version:1,routine:item}:item.payload;if(!payload)continue;all.push({id:item.id,type:t,key,payload,updatedAt:item.updatedAt||item.savedAt||null,revision:JSON.stringify(item)});}}return all.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));}
 function save(storage,payload,id=null,expected){payload=rename(payload,title(payload));const t=type(payload),key=keys[t];if(!key)throw Error('Unknown visual type.');const items=JSON.parse(storage.getItem(key)||'[]');if(!Array.isArray(items))throw Error('Device library could not be read.');const index=items.findIndex(x=>x.id===id);if(id&&(index<0||(expected&&JSON.stringify(items[index])!==expected)))throw Error('This saved board changed in another tab. Reopen it or use Save as to keep your edits.');const now=Date.now(),record=t==='routine'?{...payload.routine,id:id||crypto.randomUUID(),savedAt:now,updatedAt:now}:{id:id||crypto.randomUUID(),payload,updatedAt:now};if(index<0)items.push(record);else items[index]=record;storage.setItem(key,JSON.stringify(items));return {id:record.id,type:t,key,payload,updatedAt:now,revision:JSON.stringify(record)};}
 function remove(storage,row){const items=JSON.parse(storage.getItem(row.key)||'[]'),found=items.find(x=>x.id===row.id);if(!found||JSON.stringify(found)!==row.revision)throw Error('This board changed. Reopen the library and try again.');storage.setItem(row.key,JSON.stringify(items.filter(x=>x.id!==row.id)));}
 const api={keys,type,title,rename,path,list,save,remove};root.BoardFiles=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
