const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const settings=require('../cloud/board-settings.js'),{createHandler}=require('../cloud/save-handler.js');
function lib(file,name){const c=vm.createContext({});vm.runInContext(fs.readFileSync(file,'utf8')+`;globalThis.result=${name}`,c);return c.result;}
const token=lib('token-board/data.js','TokenData'),homework=lib('homework-planner/data.js','HomeworkData');
const sample=()=>token.serialize(token.defaults());
test('cloud strips earned tokens, names, session history and unknown fields without changing local state',()=>{const p=sample();p.board.tokens[0].earned=true;p.board.person='private';p.board.results=[{name:'private'}];p.session={points:9};const out=settings.clean(p);assert.equal(out.board.tokens[0].earned,false);assert.equal(p.board.tokens[0].earned,true);assert.equal(JSON.stringify(out).includes('private'),false);assert.equal(out.session,undefined);token.validate(out);});
test('homework cloud templates contain no assignments, yes/no answers, dates or uploaded images',()=>{const p=homework.serialize(homework.defaults());Object.assign(p.board,{person:'private',week:'2026-10-08'});p.board.subjects[0].image='data:image/png;base64,cHJpdmF0ZQ==';p.board.subjects[0].entries[0]={homework:'yes',assignment:'private',done:true};const out=settings.clean(p);assert.equal(out.board.person,'');assert.equal(out.board.week,'');assert.equal(out.board.subjects[0].image,'');assert.deepEqual(out.board.subjects[0].entries[0],{homework:'',assignment:'',done:false});homework.validate(out);});
test('support cards and chores reset all completion data',()=>{let p={format:'visual-support-board',version:1,board:{type:'task-strip',title:'Steps',person:'private',cards:[{label:'Read',pictogramId:1,marked:true}]}};let out=settings.clean(p);assert.equal(out.board.cards[0].marked,false);assert.equal(out.board.person,'');lib('supports/data.js','SupportData').validate(out);out=settings.clean({format:'weekly-chore-chart',version:1,chart:{name:'Jobs',person:'private',week:'date',chores:[{name:'Tidy',pictogramId:null,checked:Array(7).fill(true)}]}});assert.deepEqual(out.chart.chores[0].checked,Array(7).fill(false));assert.equal(out.chart.week,'');lib('chore-chart/data.js','ChoreChartData').validate(out);});
test('self-monitor cloud setup never includes check-in records',()=>{const p={format:'self-monitor',version:1,board:{type:'self-monitor',title:'Work',duration:30,interval:5,timing:'equal',variation:1,message:'On track?',yes:1,no:.5,mismatch:0,theme:'ocean',classicColor:'#3185fc',showTimer:true,chimes:true,records:[{student:true,adult:false}],points:1}};const out=settings.clean(p);assert.equal(out.board.records,undefined);assert.equal(out.board.points,undefined);lib('self-monitor/model.js','SelfMonitor').validateSetup(out.board);});
test('routine removes arbitrary image URLs and preserves allowed layout settings',()=>{const p={format:'routine-visual-timer',version:1,routine:{name:'Routine',category:'morning',autoTotal:true,totalMinutes:5,settings:{theme:'classic',flexible:false,quiet:true,showClock:true,projTextColor:'',sounds:{chime:true,tick:false,victory:true},projFontScale:1.3,printFontScale:1.3,projIconScale:1.3,printIconScale:1.3},steps:[{name:'Read',minutes:5,pictogramId:12,imageUrl:'https://example.com/private-child-name',positions:{print:{label:{x:1,y:2}}}}]}};const out=settings.clean(p);assert.equal(out.routine.steps[0].imageUrl,'https://static.arasaac.org/pictograms/12/12_300.png');assert.equal(JSON.stringify(out).includes('private-child'),false);assert.deepEqual(out.routine.steps[0].positions,p.routine.steps[0].positions);});
test('unknown formats, oversized values and unsafe icons are rejected',()=>{assert.throws(()=>settings.clean({format:'session-results',version:1}));const p=sample();p.board.tokens[0].icon.id='<script>';assert.throws(()=>settings.clean(p));p.board.tokens[0].icon.id='star';p.board.title='x'.repeat(201);assert.throws(()=>settings.clean(p));});
function harness(){const rows=new Map();const handler=createHandler({settings,allowedOrigins:['https://routines.getadhd.care'],authenticate:async h=>h==='Bearer a'?{id:'a',email_confirmed_at:'now'}:h==='Bearer b'?{id:'b',email_confirmed_at:'now'}:null,insert:async row=>{const k=row.user_id+row.slot;if(rows.has(k))return null;rows.set(k,row);return row;},replace:async(row,revision)=>{const k=row.user_id+row.slot;if(rows.get(k)?.revision!==revision)return null;rows.set(k,row);return row;}});const call=(body,auth='a')=>handler(new Request('https://example.com',{method:'POST',headers:{Authorization:`Bearer ${auth}`,Origin:'https://routines.getadhd.care'},body:JSON.stringify(body)}));const body=()=>({payload:sample(),slot:1,revision:null,attested:true,attestationVersion:settings.VERSION});return {call,body,rows};}
test('server requires authentication and fresh explicit attestation',async()=>{const h=harness();assert.equal((await h.call(h.body(),'unknown')).status,401);assert.equal((await h.call({...h.body(),attested:false})).status,400);assert.equal((await h.call({...h.body(),attestationVersion:'old'})).status,400);assert.equal(h.rows.size,0);});
test('two slots total, insert conflicts, ownership and optimistic updates',async()=>{const h=harness();let r=await h.call(h.body());assert.equal(r.status,200);const first=(await r.json()).board;assert.equal((await h.call(h.body())).status,409);assert.equal((await h.call({...h.body(),slot:2})).status,200);assert.equal((await h.call({...h.body(),slot:3})).status,400);assert.equal((await h.call({...h.body(),revision:first.revision},'b')).status,409);assert.equal((await h.call({...h.body(),revision:first.revision})).status,200);assert.equal((await h.call({...h.body(),revision:first.revision})).status,409);assert.equal(h.rows.size,2);});
test('server independently strips results even if a caller bypasses browser filtering',async()=>{const h=harness(),b=h.body();b.payload.board.tokens[0].earned=true;b.payload.board.records=[{private:true}];const r=await h.call(b);assert.equal(r.status,200);const {board}=await r.json();assert.equal(board.payload.board.records,undefined);assert.equal(board.payload.board.tokens[0].earned,false);assert.equal(board.attestation_version,settings.VERSION);});
