const {test}=require('node:test'),assert=require('node:assert/strict'),F=require('../js/file-store.js');
function storage(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};}
const payload={format:'token-board',version:2,board:{type:'token-board',title:'Example',tokens:[]}};
test('Save updates one device board; Save as creates a separate copy',()=>{const s=storage();const first=F.save(s,payload);const updated=F.save(s,F.rename(payload,'Changed'),first.id,first.revision);assert.equal(F.list(s).length,1);assert.equal(F.title(F.list(s)[0].payload),'Changed');F.save(s,F.rename(updated.payload,'Copy'));assert.equal(F.list(s).length,2);});
test('legacy routines and boards are visible without migration or duplication',()=>{const s=storage();s.setItem(F.keys.routine,JSON.stringify([{id:'old',name:'Morning',savedAt:123,steps:[]}]));s.setItem(F.keys['token-board'],JSON.stringify([{id:'token',payload}]));const rows=F.list(s);assert.equal(rows.length,2);assert.equal(rows[0].payload.routine.name,'Morning');assert.equal(F.path(rows[1].payload),'token-board/');F.save(s,F.rename(rows[0].payload,'Renamed'),'old',rows[0].revision);assert.equal(JSON.parse(s.getItem(F.keys.routine)).length,1);});
test('a stale tab cannot overwrite or delete newer device edits',()=>{const s=storage(),old=F.save(s,payload);F.save(s,F.rename(payload,'Newer'),old.id,old.revision);assert.throws(()=>F.save(s,payload,old.id,old.revision),/changed/);assert.throws(()=>F.remove(s,old),/changed/);});
test('failed storage writes propagate instead of claiming a successful save',()=>{const s=storage();s.setItem=()=>{throw Error('Storage full');};assert.throws(()=>F.save(s,payload),/Storage full/);});
test('rename is immutable, requires a usable name and cannot introduce unknown routes',()=>{const renamed=F.rename(payload,'Renamed');assert.equal(payload.board.title,'Example');assert.equal(renamed.board.title,'Renamed');assert.throws(()=>F.rename(payload,' '));assert.throws(()=>F.path({format:'unknown'}));});
const vm=require('node:vm'),fs=require('node:fs');
test('New creates valid empty templates for each board family',()=>{const c={};vm.createContext(c);for(const file of ['supports/data.js','token-board/data.js','homework-planner/data.js','self-monitor/model.js','chore-chart/data.js','cloud/adapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);vm.runInContext('CloudBoardAdapter.open=function(p){this.result=p}; this.validators={SupportData,TokenData,HomeworkData,SelfMonitor,ChoreChartData}',c);const samples=[{format:'visual-support-board',version:1,board:{type:'first-then',title:'Old',person:'Name',layout:{rows:0,columns:0},cards:[{label:'Old',pictogramId:1,marked:true},{label:'Old',pictogramId:2,marked:false}]}},{format:'token-board',version:2,board:{}},{format:'homework-planner',version:1,board:{}},{format:'self-monitor',version:1,board:{}},{format:'weekly-chore-chart',version:1,chart:{}}];for(const p of samples){const result=c.CloudBoardAdapter.blank(p);if(p.format==='visual-support-board')c.validators.SupportData.validate(result);if(p.format==='token-board')c.validators.TokenData.validate(result);if(p.format==='homework-planner')c.validators.HomeworkData.validate(result);if(p.format==='self-monitor')c.validators.SelfMonitor.validateSetup(result.board);if(p.format==='weekly-chore-chart')c.validators.ChoreChartData.validate(result);}});
