const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../homework-planner/data.js'),'utf8')+';this.data=HomeworkData',ctx);const d=ctx.data;
test('both planner modes preserve weekly schedule, answers, assignments and completion',()=>{const b=d.defaults();b.layout='day';b.day=2;b.subjects[0].image='data:image/png;base64,YQ==';b.subjects[0].entries[0]={homework:'yes',assignment:'Read chapter 2',done:true};b.subjects[0].entries[6].assignment='Weekend project';for(const mode of ['simple','detailed']){b.mode=mode;const result=d.validate(JSON.parse(JSON.stringify(d.serialize(b))));assert.equal(JSON.stringify(result),JSON.stringify(b));}});
test('planner files reject invalid statuses, sizes, layouts and wrong formats',()=>{for(const change of [b=>b.subjects=[],b=>b.subjects=Array(9).fill(b.subjects[0]),b=>b.day=7,b=>b.layout='unknown',b=>b.subjects[0].image='https://example.com/image.png',b=>b.mode='unknown',b=>b.subjects[0].entries[0].homework='maybe',b=>b.subjects[0].entries[0].done='yes',b=>b.subjects[0].entries[0].assignment='x'.repeat(501)]){const b=d.defaults();change(b);assert.throws(()=>d.serialize(b));}assert.throws(()=>d.validate({format:'token-board',version:1,board:d.defaults()}));});
test('blank answers are distinct from no and unknown imported fields are dropped',()=>{const b=d.defaults();assert.equal(b.subjects[0].entries[0].homework,'');b.imageUrl='https://example.test';assert.equal(d.serialize(b).board.imageUrl,undefined);});

test('older planners load with weekly layout and no images, discarding obsolete start times',()=>{const b=d.defaults();delete b.layout;delete b.day;for(const s of b.subjects)delete s.image;b.times=Array(7).fill('16:00');const result=d.validate({format:'homework-planner',version:1,board:b});assert.equal(result.layout,'week');assert.equal(result.day,0);assert.equal(result.subjects[0].image,'');assert.equal(result.times,undefined);});

test('ARASAAC subject IDs roundtrip and reject invalid identifiers',()=>{const b=d.defaults();b.subjects[0].pictogramId=1234;assert.equal(d.validate(d.serialize(b)).subjects[0].pictogramId,1234);for(const id of [-1,0,1.5,'1234','https://example.com']){b.subjects[0].pictogramId=id;assert.throws(()=>d.serialize(b));}});

test('new planners start with a blank single day and print dates cross month and year boundaries',()=>{assert.equal(d.defaults().layout,'day');assert.equal(d.defaults().day,-1);assert.equal(d.dateLabel('2026-12-28',4),'01/01');assert.equal(d.dateLabel('2026-10-05',2),'10/07');assert.equal(d.dateLabel('',0),'');assert.equal(d.dateLabel('2026-02-30',0),'');assert.equal(d.dateLabel('2026-10-05',-1),'');assert.equal(d.validate(d.serialize(d.defaults())).day,-1);});
test('attached homework example retains all three subject symbols',()=>{vm.runInContext(fs.readFileSync(path.join(__dirname,'../homework-planner/presets.js'),'utf8')+';this.example=HOMEWORK_EXAMPLE',ctx);const b=d.validate(ctx.example);assert.equal(b.subjects.map(s=>s.pictogramId).join(','),'2447,36373,27604');assert.equal(b.layout,'week');});
