const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../self-monitor/model.js'),'utf8')+';this.model=SelfMonitor',ctx);const m=ctx.model;
test('equal intervals include the final partial interval without extending session',()=>{assert.equal(m.schedule(12,5).join(','),'300000,600000,720000');assert.equal(m.schedule(10,5).length,2);assert.equal(m.schedule(1,5)[0],60000);});
test('random intervals respect variation bounds and end at duration',()=>{assert.equal(m.schedule(12,5,1,()=>0).join(','),'240000,480000,720000');assert.equal(m.schedule(12,5,1,()=>1).join(','),'360000,720000');for(const args of [[0,5],[91,5],[10,0],[10,5,5],[10,5,-1]])assert.throws(()=>m.schedule(...args));});
test('default and custom scoring cover all response pairs and half-icon fills',()=>{const rules={yes:1,no:.5,mismatch:0};assert.equal(m.points(true,true,rules),1);assert.equal(m.points(false,false,rules),.5);assert.equal(m.points(false,true,rules),0);assert.equal(m.points(true,false,rules),0);assert.equal(m.points(false,true,{...rules,mismatch:2}),2);assert.equal(m.fill(1.5,0),1);assert.equal(m.fill(1.5,1),.5);assert.equal(m.fill(1.5,2),0);});
test('elapsed time stops at a check-in even after delayed timer callbacks',()=>{assert.equal(m.advance(290000,50000,300000),300000);assert.equal(m.advance(1000,-100,300000),1000);});
function app(){const nodes=new Map();function element(){return {value:'',textContent:'',disabled:false,children:[],style:{setProperty(){}},append(...els){this.children.push(...els)},replaceChildren(){this.children=[]},setAttribute(){},addEventListener(){},focus(){},showModal(){this.open=true},close(){this.open=false}};}const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};Object.entries({duration:2,interval:1,timing:'equal',variation:0,message:'Are you on track?',yesPoints:1,noPoints:.5,mismatchPoints:0}).forEach(([id,value])=>get(id).value=String(value));let now=0,callback;const context=vm.createContext({document:{getElementById:get,createElement:element},performance:{now:()=>now},setInterval:fn=>{callback=fn;},confirm:()=>true});vm.runInContext(fs.readFileSync(path.join(__dirname,'../self-monitor/model.js'),'utf8')+fs.readFileSync(path.join(__dirname,'../self-monitor/app.js'),'utf8'),context);return {get,step(ms){now+=ms;callback();},start(){get('settings').onsubmit({preventDefault(){}});}};}
test('check-ins pause work time, collect independent ratings, and finish only after final adult rating',()=>{const a=app();a.start();a.step(60000);assert.equal(a.get('who').textContent,'Student check-in');a.step(20000);assert.equal(a.get('remaining').textContent,'1:00');a.get('answerNo').onclick();assert.equal(a.get('who').textContent,'Adult check-in');a.get('answerNo').onclick();assert.equal(a.get('score').textContent,'0.5 points');a.step(60000);assert.equal(a.get('phase').textContent,'Check-in time');a.get('answerYes').onclick();a.get('answerYes').onclick();assert.equal(a.get('score').textContent,'1.5 points');assert.equal(a.get('phase').textContent,'Session complete');assert.equal(a.get('results').children.length,2);});
test('manual pause excludes waiting and reset restores editable setup',()=>{const a=app();a.start();a.step(10000);a.get('pause').onclick();a.step(50000);assert.equal(a.get('remaining').textContent,'1:50');a.get('pause').onclick();a.step(10000);assert.equal(a.get('remaining').textContent,'1:40');a.get('reset').onclick();assert.equal(a.get('options').disabled,false);assert.equal(a.get('score').textContent,'0 points');});
