const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../self-monitor/model.js'),'utf8')+';this.model=SelfMonitor',ctx);const m=ctx.model;
test('equal intervals include the final partial interval without extending session',()=>{assert.equal(m.schedule(12,5).join(','),'300000,600000,720000');assert.equal(m.schedule(10,5).length,2);assert.equal(m.schedule(1,5)[0],60000);});
test('random intervals respect variation bounds and end at duration',()=>{assert.equal(m.schedule(12,5,1,()=>0).join(','),'240000,480000,720000');assert.equal(m.schedule(12,5,1,()=>1).join(','),'360000,720000');for(const args of [[0,5],[91,5],[10,0],[10,5,5],[10,5,-1]])assert.throws(()=>m.schedule(...args));});
test('default and custom scoring cover all response pairs and half-icon fills',()=>{const rules={yes:1,no:.5,mismatch:0};assert.equal(m.points(true,true,rules),1);assert.equal(m.points(false,false,rules),.5);assert.equal(m.points(false,true,rules),0);assert.equal(m.points(true,false,rules),0);assert.equal(m.points(false,true,{...rules,mismatch:2}),2);assert.equal(m.fill(1.5,0),1);assert.equal(m.fill(1.5,1),.5);assert.equal(m.fill(1.5,2),0);});
test('elapsed time stops at a check-in even after delayed timer callbacks',()=>{assert.equal(m.advance(290000,50000,300000),300000);assert.equal(m.advance(1000,-100,300000),1000);});
function app(){const nodes=new Map();function element(){return {value:'',textContent:'',disabled:false,children:[],style:{setProperty(){}},append(...els){this.children.push(...els)},replaceChildren(){this.children=[]},setAttribute(){},addEventListener(){},focus(){},showModal(){this.open=true},close(){this.open=false}};}const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};Object.entries({duration:2,interval:1,timing:'equal',variation:0,message:'Are you on track?',yesPoints:1,noPoints:.5,mismatchPoints:0}).forEach(([id,value])=>get(id).value=String(value));let now=0,callback;const context=vm.createContext({document:{getElementById:get,createElement:element},performance:{now:()=>now},setInterval:fn=>{callback=fn;},confirm:()=>true});vm.runInContext(fs.readFileSync(path.join(__dirname,'../self-monitor/model.js'),'utf8')+fs.readFileSync(path.join(__dirname,'../self-monitor/app.js'),'utf8'),context);return {get,chimeSpy(fn){context.chimeSpy=fn;vm.runInContext('playPromptChime=chimeSpy',context);},snapshot(){return JSON.parse(vm.runInContext('JSON.stringify(session)',context));},step(ms){now+=ms;callback();},start(){get('settings').onsubmit({preventDefault(){}});}};}
test('check-ins pause work time, collect independent ratings, and finish only after final adult rating',()=>{const a=app();a.start();a.step(60000);assert.equal(a.get('who').textContent,'Student check-in');a.step(20000);assert.equal(a.get('remaining').textContent,'1:00');a.get('answerNo').onclick();assert.equal(a.get('who').textContent,'Adult check-in');a.get('answerNo').onclick();assert.equal(a.get('score').textContent,'0.5 points');a.step(60000);assert.equal(a.get('phase').textContent,'Check-in time');a.get('answerYes').onclick();a.get('answerYes').onclick();assert.equal(a.get('score').textContent,'1.5 points');assert.equal(a.get('phase').textContent,'Session complete');assert.equal(a.get('results').children.length,2);});
test('manual pause excludes waiting and reset restores editable setup',()=>{const a=app();a.start();a.step(10000);a.get('pause').onclick();a.step(50000);assert.equal(a.get('remaining').textContent,'1:50');a.get('pause').onclick();a.step(10000);assert.equal(a.get('remaining').textContent,'1:40');a.get('reset').onclick();assert.equal(a.get('options').disabled,false);assert.equal(a.get('score').textContent,'0 points');});

test('saved self-monitor setups preserve options and reject unsafe or invalid settings',()=>{const b={title:'Study',duration:30,interval:5,timing:'random',variation:1,message:'On track?',yes:1,no:.5,mismatch:0,theme:'forest',showTimer:false};const saved=m.validateSetup(JSON.parse(JSON.stringify(b)));assert.equal(saved.theme,'forest');assert.equal(saved.showTimer,false);assert.equal(saved.no,.5);assert.equal(saved.type,'self-monitor');for(const change of [{variation:5},{duration:91},{yes:-1},{no:.3},{theme:'unknown'},{showTimer:'no'}])assert.throws(()=>m.validateSetup({...b,...change}));assert.equal(m.validateSetup({...b,student:'private answer'}).student,undefined);});

test('exit ticket records retain actual work time and each independent rating',()=>{const a=app();a.start();a.step(60000);a.get('answerNo').onclick();a.get('answerNo').onclick();a.step(60000);a.get('answerYes').onclick();a.get('answerNo').onclick();const s=a.snapshot();assert.deepEqual(s.records,[{number:1,elapsed:60000,student:false,adult:false,points:.5},{number:2,elapsed:120000,student:true,adult:false,points:0}]);assert.equal(s.points,.5);assert.ok(Number.isFinite(Date.parse(s.startedAt)));a.get('reset').onclick();assert.equal(a.snapshot(),null);});
function recoveryFixture(stage='running'){const setup={title:'Study',duration:2,interval:1,timing:'equal',variation:0,message:'On track?',yes:1,no:.5,mismatch:0,theme:'forest',showTimer:false};return {version:1,savedAt:1000,setup,session:{title:'Study',message:'On track?',startedAt:'2026-10-08T16:00:00Z',total:120000,ends:[60000,120000],index:0,elapsed:10000,stage,records:[],points:0,rules:{yes:1,no:.5,mismatch:0}}};}
test('returning to a running session counts time away and stops at first unanswered check-in',()=>{let r=m.restoreSession(recoveryFixture(),21000);assert.equal(r.session.elapsed,30000);assert.equal(r.session.stage,'running');r=m.restoreSession(recoveryFixture(),999999);assert.equal(r.session.elapsed,60000);assert.equal(r.session.stage,'student');assert.equal(r.session.index,0);});
test('navigation preserves paused sessions, pending adult answers, completed records and display settings',()=>{const paused=m.restoreSession(recoveryFixture('paused'),999999);assert.equal(paused.session.elapsed,10000);assert.equal(paused.setup.showTimer,false);const pending=recoveryFixture('adult');pending.session.student=false;pending.session.elapsed=60000;const restored=m.restoreSession(pending,999999);assert.equal(restored.session.student,false);assert.equal(restored.session.stage,'adult');const done=recoveryFixture('finished');Object.assign(done.session,{index:2,elapsed:120000,records:[{number:1,elapsed:60000,student:false,adult:false,points:.5},{number:2,elapsed:120000,student:true,adult:true,points:1}]});assert.equal(m.restoreSession(done,999999).session.points,1.5);done.session.ends=[-1];assert.throws(()=>m.restoreSession(done));});
test('Classic color survives save and recovery while older setups receive a default',()=>{const record=recoveryFixture('paused');record.setup.theme='classic';record.setup.classicColor='#ab1234';assert.equal(m.validateSetup(record.setup).classicColor,'#ab1234');assert.equal(m.restoreSession(record).setup.classicColor,'#ab1234');delete record.setup.classicColor;assert.equal(m.validateSetup(record.setup).classicColor,'#3185fc');record.setup.classicColor='red; background:url(x)';assert.throws(()=>m.validateSetup(record.setup));});

test('student prompt plays one chime and adult prompt plays two',()=>{const a=app(),chimes=[];a.chimeSpy(count=>chimes.push(count));a.start();a.step(60000);assert.deepEqual(chimes,[1]);a.get('answerYes').onclick();assert.deepEqual(chimes,[1,2]);a.get('answerNo').onclick();assert.deepEqual(chimes,[1,2]);});
test('check-in sound setting persists with a backward-compatible default',()=>{const b=recoveryFixture().setup;assert.equal(m.validateSetup(b).chimes,true);assert.equal(m.validateSetup({...b,chimes:false}).chimes,false);assert.throws(()=>m.validateSetup({...b,chimes:'yes'}));});
test('new projection themes survive setup export/import and session recovery',()=>{for(const theme of ['garden','unicorn','chef','scientist']){const record=recoveryFixture('paused');record.setup.theme=theme;const setup=m.validateSetup(JSON.parse(JSON.stringify(record.setup)));assert.equal(setup.theme,theme);assert.equal(m.restoreSession({...record,setup}).setup.theme,theme);}});
