const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,'../token-board/data.js'),'utf8')+';this.data=TokenData',ctx);const data=ctx.data;
test('mixed-source board roundtrip preserves pictures, reward and progress',()=>{const b=data.defaults();['material','openmoji','arasaac','dicebear'].forEach((source,i)=>b.tokens[i].icon={source,id:source==='arasaac'?'1234':'star',label:'Picture'});b.tokens[1].earned=true;b.sound=true;assert.equal(JSON.stringify(data.validate(JSON.parse(JSON.stringify(data.serialize(b))))),JSON.stringify(b));});
test('imports reject unknown sources, unsafe identifiers and invalid options',()=>{for(const change of [b=>b.tokens=[],b=>b.tokens=Array(13).fill(b.tokens[0]),b=>b.tokens[0].icon.id='../../secret',b=>b.rewardIcon.source='icons8',b=>b.tokens[0].icon={source:'arasaac',id:'abc',label:'X'},b=>b.tokens[0].earned='true',b=>b.extraSets=4,b=>b.color='url(evil)',b=>b.font='unknown',b=>b.title='x'.repeat(101)]){const b=data.defaults();change(b);assert.throws(()=>data.serialize(b));}});
test('remote picture URLs use allowlisted providers and drop imported extra fields',()=>{assert.equal(data.url({source:'material',id:'star',label:'Star'}),'https://api.iconify.design/material-symbols/star.svg');assert.equal(data.url({source:'arasaac',id:'123',label:'X'}),'https://static.arasaac.org/pictograms/123/123_300.png');const b=data.defaults();b.imageUrl='javascript:alert(1)';assert.equal(data.serialize(b).board.imageUrl,undefined);assert.equal(b.sound,false);});
test('DiceBear generates deterministic local SVG images without hosted requests',()=>{const c=vm.createContext({structuredClone,TextEncoder,btoa});vm.runInContext(fs.readFileSync(path.join(__dirname,'../token-board/characters.js'),'utf8'),c);const first=c.TokenCharacters.url('robot-1');assert.match(first,/^data:image\/svg\+xml/);assert.equal(first,c.TokenCharacters.url('robot-1'));assert.notEqual(first,c.TokenCharacters.url('robot-2'));});

test('old version 2 boards receive safe theme and motion defaults',()=>{const p=data.serialize(data.defaults());delete p.board.theme;delete p.board.motion;assert.equal(data.validate(p).theme,'classic');assert.equal(data.validate(p).motion,true);});
test('themes and character styles survive sharing and unknown values are rejected',()=>{for(const theme of Object.keys(data.themes)){const b=data.defaults();b.theme=theme;b.font=data.themes[theme].font;b.color=data.themes[theme].color;b.motion=false;for(const style of data.characterStyles){b.tokens[0].icon={source:'dicebear',id:'character-1',style,label:style};const result=data.validate(data.serialize(b));assert.equal(result.tokens[0].icon.style,style);assert.equal(result.theme,theme);assert.equal(result.motion,false);}}const b=data.defaults();b.theme='bad';assert.throws(()=>data.serialize(b));b.theme='classic';b.tokens[0].icon={source:'dicebear',id:'one',style:'bad',label:'bad'};assert.throws(()=>data.serialize(b));});
test('all character styles render, with native animation enabled only on supported projection styles',()=>{const c=vm.createContext({structuredClone,TextEncoder,btoa});try{vm.runInContext(fs.readFileSync(path.join(__dirname,'../token-board/characters.js'),'utf8'),c);for(const [key,style] of Object.entries(c.TokenCharacters.styles)){const still=c.TokenCharacters.url('test',key,false),animated=c.TokenCharacters.url('test',key,true);assert.match(still,/^data:image/);if(style.animated){assert.notEqual(still,animated);assert.match(decodeURIComponent(animated),/@keyframes/);}}}catch(e){throw new Error(e.message);}});
