const $=id=>document.getElementById(id);
let session=null,lastTime=0;
let playPromptChime=()=>{};
const smile='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16zM8.5 11a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zm7 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM7 14a5.2 5.2 0 0 0 10 0H7z"/></svg>';
function timeText(ms){const seconds=Math.ceil(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function render(){const total=session?.total??Number($('duration').value)*60000,elapsed=session?.elapsed??0;$('remaining').textContent=timeText(total-elapsed);$('clock').style.setProperty('--progress',`${100*(1-elapsed/total)}%`);$('phase').textContent=!session?'Ready to begin':session.stage==='finished'?'Session complete':session.stage==='running'?'Work time':session.stage==='paused'?'Paused':'Check-in time';$('pause').disabled=!session||!['running','paused'].includes(session.stage);$('pause').textContent=session?.stage==='paused'?'Resume':'Pause';$('reset').disabled=!session;$('options').disabled=!!session;$('start').disabled=!!session;}
let pointIcon=()=>smile;
function tokens(){const points=session?.points??0,capacity=session?Math.ceil(session.ends.length*Math.max(...Object.values(session.rules))):6;$('score').textContent=`${points} ${points===1?'point':'points'}`;$('tokens').replaceChildren();for(let i=0;i<capacity;i++){const token=document.createElement('span');token.className='token';token.setAttribute('aria-hidden','true');token.innerHTML=pointIcon();const lit=document.createElement('span');lit.className='token-fill';lit.style.setProperty('--fill',`${SelfMonitor.fill(points,i)*100}%`);lit.innerHTML=pointIcon();token.append(lit);$('tokens').append(token);}$('tokens').setAttribute('aria-label',`${points} points earned out of ${capacity} possible`);}
$('duration').oninput=()=>{$('durationValue').textContent=`${$('duration').value} minutes`;render();};$('timing').onchange=()=>{$('variationLabel').hidden=$('timing').value!=='random';};
$('settings').onsubmit=event=>{event.preventDefault();try{const duration=Number($('duration').value),ends=SelfMonitor.schedule(duration,Number($('interval').value),$('timing').value==='random'?Number($('variation').value):0);session={startedAt:new Date().toISOString(),records:[],title:$('setupName').value||'Self-monitor session',total:duration*60000,ends,index:0,elapsed:0,stage:'running',points:0,message:$('message').value.trim()||'Are you on track?',rules:{yes:Number($('yesPoints').value),no:Number($('noPoints').value),mismatch:Number($('mismatchPoints').value)}};lastTime=performance.now();$('results').replaceChildren();$('status').textContent='Session started.';$('progress').textContent=`0 of ${ends.length} check-ins complete`;tokens();render();}catch(e){$('status').textContent=e.message;}};
function tick(){if(session?.stage!=='running')return;const now=performance.now();session.elapsed=SelfMonitor.advance(session.elapsed,now-lastTime,session.ends[session.index]);lastTime=now;if(session.elapsed>=session.ends[session.index]){session.stage='student';$('who').textContent='Student check-in';$('question').textContent=session.message;$('answerHelp').textContent='Choose your answer, then let the adult take a turn.';$('checkin').showModal();playPromptChime(1);$('answerYes').focus();}render();}
setInterval(tick,200);
$('pause').onclick=()=>{if(session?.stage==='running'){tick();if(session.stage==='running')session.stage='paused';}else if(session?.stage==='paused'){session.stage='running';lastTime=performance.now();}render();};
$('reset').onclick=()=>{if(!session||!confirm('Reset this session and clear its points and answers?'))return;session=null;$('checkin').close();$('results').replaceChildren();$('progress').textContent='Set up your session, then press Start.';$('status').textContent='Session reset.';tokens();render();};
function answer(value){if(session?.stage==='student'){session.student=value;session.stage='adult';$('who').textContent='Adult check-in';$('question').textContent='Do you agree?';$('answerHelp').textContent=`The student answered ${value?'Yes':'No'}. Give your own on-track rating: Yes = on track; No = off track.`;playPromptChime(2);$('answerYes').focus();return;}if(session?.stage!=='adult')return;const earned=SelfMonitor.points(session.student,value,session.rules);session.points+=earned;session.records.push({number:session.index+1,elapsed:session.elapsed,student:session.student,adult:value,points:earned});const row=document.createElement('li');row.textContent=`Check-in ${session.index+1}: Student ${session.student?'Yes':'No'}, adult ${value?'Yes':'No'} — ${earned} points`; $('results').append(row);session.index++;session.stage=session.index===session.ends.length?'finished':'running';lastTime=performance.now();$('checkin').close();$('progress').textContent=`${session.index} of ${session.ends.length} check-ins complete`;$('status').textContent=session.stage==='finished'?`Session complete. You earned ${session.points} points.`:`${earned} points earned. Timer resumed.`;tokens();render();}
$('answerYes').onclick=()=>answer(true);$('answerNo').onclick=()=>answer(false);$('checkin').addEventListener('cancel',event=>event.preventDefault());tokens();render();
