// Each star has independent position, speed and phase; the animation stays subtle.
const stars=document.createElement('div');stars.className='space-stars';stars.setAttribute('aria-hidden','true');
for(let i=0;i<70;i++){const star=document.createElement('span');star.style.left=`${Math.random()*100}%`;star.style.top=`${Math.random()*100}%`;star.style.setProperty('--twinkle-duration',`${5+Math.random()*10}s`);star.style.setProperty('--twinkle-delay',`${-Math.random()*15}s`);star.style.setProperty('--star-opacity',String(.35+Math.random()*.3));star.style.width=star.style.height=`${1+Math.random()*1.5}px`;stars.append(star);}$('sessionView').prepend(stars);
let chimeContext=null;const activeChimes=new Set();
function unlockChimes(){if(!$('chimes').checked)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;chimeContext??=new Audio();if(chimeContext.state==='suspended')chimeContext.resume().catch(()=>{});}catch{}}
document.addEventListener('pointerdown',unlockChimes);document.addEventListener('keydown',unlockChimes);
playPromptChime=count=>{if(!$('chimes').checked)return;unlockChimes();if(!chimeContext||chimeContext.state!=='running')return;for(let i=0;i<count;i++){const start=chimeContext.currentTime+.03+i*.5;for(const [frequency,volume] of [[880,.10],[1320,.025]]){const oscillator=chimeContext.createOscillator(),gain=chimeContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(volume,start+.015);gain.gain.exponentialRampToValueAtTime(.0001,start+.42);oscillator.connect(gain);gain.connect(chimeContext.destination);activeChimes.add(oscillator);oscillator.onended=()=>{activeChimes.delete(oscillator);oscillator.disconnect();gain.disconnect();};oscillator.start(start);oscillator.stop(start+.45);}}};
$('chimes').addEventListener('change',()=>{if($('chimes').checked)unlockChimes();else for(const sound of activeChimes){try{sound.stop();}catch{}}});

for(const kind of ['petals','bubbles']){const layer=document.createElement('div');layer.className='theme-particles '+kind;layer.setAttribute('aria-hidden','true');for(let i=0;i<16;i++){const particle=document.createElement('span');particle.style.left=`${Math.random()*100}%`;particle.style.setProperty('--duration',`${18+Math.random()*20}s`);particle.style.setProperty('--delay',`${-Math.random()*38}s`);layer.append(particle);}$('sessionView').prepend(layer);}
for(const kind of ['autumn','winter','eighties','valentine']){const layer=document.createElement('div');layer.className=`theme-particles seasonal-${kind}`;layer.setAttribute('aria-hidden','true');for(let i=0;i<14;i++){const p=document.createElement('span');p.style.left=`${Math.random()*100}%`;p.style.setProperty('--duration',`${(kind==='eighties'?65:28)+Math.random()*30}s`);p.style.setProperty('--delay',`${-Math.random()*90}s`);p.style.setProperty('--shape-color',['#ff55d5','#64fff2','#fff05c'][i%3]);if(kind==='winter')p.textContent='❄';else if(kind==='valentine')p.innerHTML='<svg viewBox="0 0 24 24"><path d="M12 22 2 12C-5 3 6-3 12 5c6-8 17-2 10 7z"/></svg>';layer.append(p);}$('sessionView').prepend(layer);}
