const setupKey='routineVisualTimer.selfMonitor.v1';let savedId=null;
function currentPayload(){return {format:'self-monitor',version:1,board:SelfMonitor.validateSetup({type:'self-monitor',title:$('setupName').value,duration:Number($('duration').value),interval:Number($('interval').value),timing:$('timing').value,variation:Number($('variation').value),message:$('message').value,yes:Number($('yesPoints').value),no:Number($('noPoints').value),mismatch:Number($('mismatchPoints').value),theme:$('theme').value,showTimer:$('showTimer').checked})};}
function readSetup(payload){if(payload?.format!=='self-monitor'||payload.version!==1)throw Error('Choose a self-monitor setup exported from this site.');return SelfMonitor.validateSetup(payload.board);}
function appearance(){document.body.dataset.theme=$('theme').value;$('clock').hidden=!$('showTimer').checked;$('toggleTimer').textContent=$('showTimer').checked?'Hide timer':'Show timer';}
$('theme').onchange=appearance;$('showTimer').onchange=appearance;$('toggleTimer').onclick=()=>{$('showTimer').checked=!$('showTimer').checked;appearance();};
function openSetup(b){if(session)throw Error('Reset the current session before loading another setup.');for(const [id,value] of Object.entries({setupName:b.title,duration:b.duration,interval:b.interval,timing:b.timing,variation:b.variation,message:b.message,yesPoints:b.yes,noPoints:b.no,mismatchPoints:b.mismatch,theme:b.theme}))$(id).value=value;$('showTimer').checked=b.showTimer;$('duration').oninput();$('timing').onchange();appearance();}
function library(){const items=JSON.parse(localStorage.getItem(setupKey)||'[]');if(!Array.isArray(items))throw Error('Saved setups could not be read.');return items;}
function refreshSetups(){$('savedBoards').replaceChildren(new Option('Choose a saved setup',''));try{library().forEach(item=>$('savedBoards').append(new Option(item.payload.board.title,item.id)));$('savedBoards').value=savedId||'';}catch(e){$('status').textContent=e.message;}}
function report(fn){try{fn();}catch(e){$('status').textContent=e.message;}}
$('saveBoard').onclick=()=>report(()=>{const payload=currentPayload(),items=library(),id=savedId||crypto.randomUUID(),index=items.findIndex(x=>x.id===id),entry={id,payload};if(index<0)items.push(entry);else items[index]=entry;localStorage.setItem(setupKey,JSON.stringify(items));savedId=id;refreshSetups();$('status').textContent='Setup saved in this browser. Session results are not included.';});
$('loadBoard').onclick=()=>report(()=>{const entry=library().find(x=>x.id===$('savedBoards').value);if(!entry)throw Error('Choose a saved setup.');openSetup(readSetup(entry.payload));savedId=entry.id;$('status').textContent='Setup loaded.';});
$('deleteBoard').onclick=()=>report(()=>{const id=$('savedBoards').value;if(!id)return;if(!confirm('Delete this saved setup?'))return;localStorage.setItem(setupKey,JSON.stringify(library().filter(x=>x.id!==id)));if(savedId===id)savedId=null;refreshSetups();});
$('exportBoard').onclick=()=>report(()=>{const payload=currentPayload(),url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`self-monitor-${payload.board.title.replace(/[^a-z0-9_-]/gi,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('importBoard').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{try{const file=$('importFile').files[0];if(!file)return;if(file.size>100000)throw Error('Choose a setup smaller than 100 KB.');openSetup(readSetup(JSON.parse(await file.text())));savedId=null;refreshSetups();$('status').textContent='Imported. Save board to keep this setup.';}catch(e){$('status').textContent=e.message;}finally{$('importFile').value='';}};
function projection(on){document.body.classList.toggle('projection',on);$('exitProject').hidden=!on;$('projectStart').hidden=!on;}
$('project').onclick=async()=>{projection(true);try{await document.documentElement.requestFullscreen();}catch{}$('exitProject').focus();};
async function exitProjection(){if(!document.body.classList.contains('projection'))return;projection(false);if(document.fullscreenElement)await document.exitFullscreen();$('project').focus();}
$('exitProject').onclick=exitProjection;document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)projection(false);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('checkin').open)exitProjection();});
$('projectStart').onclick=()=>{if(session)return;const valid=$('settings').reportValidity();if(valid)$('settings').requestSubmit();if(!$('status').textContent.includes('started')&&!session)exitProjection();};
const oldRender=render;render=function(){oldRender();$('projectStart').disabled=!!session;$('printExit').disabled=!session?.records.length||!['running','paused','finished'].includes(session.stage);};
const oldReset=$('reset').onclick;$('reset').onclick=()=>{const before=session;oldReset();if(before&&!session&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const target=$('clock').hidden?$('tokens'):$('clock');target.animate([{transform:'scale(.75) rotate(-12deg)'},{transform:'scale(1.08) rotate(8deg)',offset:.65},{transform:'scale(1) rotate(0)'}],{duration:650,easing:'ease-out'});}};
$('printCard').onclick=()=>report(()=>{const b=currentPayload().board;if(session?.stage==='running')$('pause').onclick();const card=$('studentCard');card.replaceChildren();const title=document.createElement('h1');title.textContent=b.title;const name=document.createElement('p');name.textContent='Name: __________________________    Date: ______________';const prompt=document.createElement('h2');prompt.textContent=b.message;const instructions=document.createElement('p');instructions.textContent=`Circle your answer at each check-in. Ask an adult for their own rating, then record points. Both Yes: ${b.yes}; both No: ${b.no}; mismatch: ${b.mismatch}. Session: ${b.duration} minutes; ${b.timing==='random'?`random intervals around ${b.interval} minutes (±${b.variation})`:`every ${b.interval} minutes`}.`;
const table=document.createElement('table');table.className='card-table';const head=document.createElement('thead');const row=document.createElement('tr');for(const label of ['Check-in','Student','Adult','Points']){const th=document.createElement('th');th.textContent=label;row.append(th);}head.append(row);table.append(head);const body=document.createElement('tbody');const count=session?.ends.length??Math.ceil(b.duration/(b.timing==='random'?b.interval-b.variation:b.interval));for(let i=0;i<count;i++){const tr=document.createElement('tr');for(const text of [String(i+1),'Yes / No','Yes / No','________']){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);}table.append(body);const footer=document.createElement('footer');footer.className='card-footer';footer.append('Total points: ______   Applied Behavioral Health Practice');const qr=document.createElement('img');qr.src='../assets/qr/routines.png';qr.alt='Routines website QR code';footer.append(qr);card.append(title,name,prompt,instructions,table,footer);window.print();});
appearance();refreshSetups();

$('printExit').onclick=()=>report(()=>{
 if(!session?.records.length)throw Error('Complete at least one check-in before printing an exit ticket.');
 if(session.stage==='running')$('pause').onclick();
 if(!['paused','finished'].includes(session.stage))throw Error('Finish the current check-in, then print your exit ticket.');
 const card=$('studentCard');card.replaceChildren();
 const add=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;card.append(el);return el;};
 add('h1',`${session.title} — Exit ticket`);
 add('p',`Name: __________________________   Period: ______________`);
 add('p',`Session started: ${new Date(session.startedAt).toLocaleString()} · ${session.stage==='finished'?'Completed session':'Session in progress — results so far'}`);
 add('h2',session.message);
 add('p',`Work time: ${timeText(session.elapsed)} of ${timeText(session.total)} · Completed check-ins: ${session.records.length} of ${session.ends.length}`);
 const matches=session.records.filter(r=>r.student===r.adult).length;
 const possible=session.records.length*Math.max(...Object.values(session.rules));
 add('p',`Points earned: ${session.points} of ${possible} possible for completed check-ins · Matching ratings: ${matches} of ${session.records.length}`);
 add('p',`Scoring: Both Yes = ${session.rules.yes}; both No = ${session.rules.no}; mismatch = ${session.rules.mismatch}.`);
 const table=document.createElement('table');table.className='card-table';const head=document.createElement('thead'),header=document.createElement('tr');
 for(const text of ['Check-in','Work time','Student','Adult','Points']){const th=document.createElement('th');th.textContent=text;header.append(th);}head.append(header);table.append(head);
 const body=document.createElement('tbody');for(const r of session.records){const tr=document.createElement('tr');for(const text of [r.number,timeText(r.elapsed),r.student?'Yes':'No',r.adult?'Yes':'No',r.points]){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);}table.append(body);card.append(table);
 const reflection=add('section','');reflection.className='exit-reflection';for(const question of ['Something that helped me stay on track:','One thing I will try next time:']){const p=document.createElement('p');p.textContent=question;reflection.append(p);const line=document.createElement('p');line.textContent='________________________________________________________________';reflection.append(line);}
 const footer=document.createElement('footer');footer.className='card-footer';footer.append('Applied Behavioral Health Practice · routines.getadhd.care');const qr=document.createElement('img');qr.src='../assets/qr/routines.png';qr.alt='Routines website QR code';footer.append(qr);card.append(footer);
 window.print();
});
