let planner=HomeworkData.defaults(),savedId=null;
const $=id=>document.getElementById(id),key='routineVisualTimer.homework.v1',say=text=>{$('status').textContent=text;};
function heading(){$('printTitle').textContent=planner.title||'Homework planner';$('printDetails').textContent=[planner.person,planner.week?`Week starting ${planner.week}`:''].filter(Boolean).join(' · ');$('versionLabel').textContent=planner.mode==='simple'?'Is there homework? Check Yes or No for each subject.':'Write each day’s homework and check Done when finished.';}
function printText(value,cls=''){const el=document.createElement('span');el.className='print-only '+cls;el.textContent=value;return el;}
function render(){
 heading();$('head').replaceChildren();$('body').replaceChildren();const count=planner.weekends?7:5;
 const row=document.createElement('tr'),subjectHead=document.createElement('th');subjectHead.textContent='Subject';subjectHead.scope='col';subjectHead.className='subject-cell';row.append(subjectHead);
 for(let day=0;day<count;day++){const th=document.createElement('th');th.scope='col';th.append(HomeworkData.days[day]);const label=document.createElement('label');label.textContent='Start time';const input=document.createElement('input');input.type='time';input.value=planner.times[day];input.setAttribute('aria-label',`${HomeworkData.days[day]} homework start time`);const printed=printText(planner.times[day]||'Start: ______');input.oninput=()=>{planner.times[day]=input.value;printed.textContent=input.value||'Start: ______';};label.append(input);th.append(label,printed);row.append(th);}$('head').append(row);
 planner.subjects.forEach((subject,index)=>{const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';const input=document.createElement('input');input.type='text';input.maxLength=60;input.value=subject.name;input.setAttribute('aria-label',`Subject ${index+1}`);input.onchange=()=>{subject.name=input.value;render();};const remove=document.createElement('button');remove.textContent='Remove subject';remove.className='no-print';remove.disabled=planner.subjects.length===1;remove.onclick=()=>{planner.subjects.splice(index,1);render();};th.append(input,printText(subject.name),remove);tr.append(th);
  for(let day=0;day<count;day++){const e=subject.entries[day],td=document.createElement('td'),context=`${subject.name||`Subject ${index+1}`} on ${HomeworkData.days[day]}`;
   if(planner.mode==='simple'){for(const value of ['yes','no']){const label=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.name=`homework-${index}-${day}`;radio.checked=e.homework===value;radio.setAttribute('aria-label',`${value==='yes'?'Yes':'No'} homework: ${context}`);radio.onchange=()=>{e.homework=value;};label.append(radio,value==='yes'?' Yes':' No');td.append(label);}const clear=document.createElement('button');clear.textContent='Clear';clear.className='no-print';clear.setAttribute('aria-label',`Clear answer: ${context}`);clear.onclick=()=>{e.homework='';render();};td.append(clear);}
   else{const text=document.createElement('textarea');text.maxLength=500;text.value=e.assignment;text.setAttribute('aria-label',`Homework: ${context}`);const printed=printText(e.assignment,'assignment-print');text.oninput=()=>{e.assignment=text.value;printed.textContent=e.assignment;};const label=document.createElement('label'),done=document.createElement('input');done.type='checkbox';done.checked=e.done;done.setAttribute('aria-label',`Done: ${context}`);done.onchange=()=>{e.done=done.checked;td.classList.toggle('homework-done',e.done);};td.classList.toggle('homework-done',e.done);label.append(done,' Done');td.append(text,printed,label);}tr.append(td);
  }$('body').append(tr);
 });$('addSubject').disabled=planner.subjects.length>=8;
}
function sync(){for(const field of ['title','person','week','mode'])$(field).value=planner[field];$('weekends').checked=planner.weekends;render();}
for(const field of ['title','person','week'])$(field).oninput=()=>{planner[field]=$(field).value;heading();};$('mode').onchange=()=>{planner.mode=$('mode').value;render();};$('weekends').onchange=()=>{planner.weekends=$('weekends').checked;render();};$('addSubject').onclick=()=>{if(planner.subjects.length<8){planner.subjects.push(HomeworkData.subject('New subject'));render();}};
function currentPayload(){return HomeworkData.serialize(planner);}
function library(){const saved=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(saved))throw Error('Saved planners could not be read.');saved.forEach(entry=>{if(typeof entry.id!=='string')throw Error('Invalid saved planner.');HomeworkData.validate(entry.payload);});return saved;}
function refresh(){$('savedBoards').replaceChildren(new Option('Choose a saved planner',''));try{library().forEach(entry=>$('savedBoards').append(new Option(entry.payload.board.title,entry.id)));$('savedBoards').value=savedId||'';}catch(e){say(e.message);}}
$('saveBoard').onclick=()=>{try{if(!planner.title.trim())throw Error('Give your planner a name.');const saved=library(),id=savedId||crypto.randomUUID(),entry={id,payload:currentPayload()},index=saved.findIndex(item=>item.id===id);if(index<0)saved.push(entry);else saved[index]=entry;localStorage.setItem(key,JSON.stringify(saved));savedId=id;refresh();say('Planner saved in this browser.');}catch(e){say(`Could not save: ${e.message}`);}};
$('loadBoard').onclick=()=>{try{const entry=library().find(item=>item.id===$('savedBoards').value);if(!entry)throw Error('Choose a saved planner first.');planner=HomeworkData.validate(entry.payload);savedId=entry.id;sync();say('Planner loaded.');}catch(e){say(e.message);}};
$('deleteBoard').onclick=()=>{try{const saved=library(),entry=saved.find(item=>item.id===$('savedBoards').value);if(!entry)throw Error('Choose a saved planner first.');if(!confirm(`Delete the saved copy of “${entry.payload.board.title}”? The open planner stays on screen.`))return;localStorage.setItem(key,JSON.stringify(saved.filter(item=>item.id!==entry.id)));if(savedId===entry.id)savedId=null;refresh();say('Saved copy deleted.');}catch(e){say(e.message);}};
$('exportBoard').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(currentPayload(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`homework-${planner.title.replace(/[^a-z0-9_-]+/gi,'-')||'planner'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importBoard').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{const file=$('importFile').files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('Choose a file smaller than 1 MB.');const validated=HomeworkData.validate(JSON.parse(await file.text()));planner=validated;savedId=null;sync();refresh();say('Imported. Save board to keep this planner in your browser.');}catch(e){say(`Could not import: ${e.message} Your planner is unchanged.`);}finally{$('importFile').value='';}};
$('printBoard').onclick=()=>window.print();sync();refresh();
