let planner=HomeworkData.defaults(),savedId=null;
const $=id=>document.getElementById(id),key='routineVisualTimer.homework.v1',say=text=>{$('status').textContent=text;};
function heading(){$('printTitle').textContent=planner.title||'Homework planner';$('printDetails').textContent=[planner.person,planner.week?`Week starting ${planner.week}`:''].filter(Boolean).join(' · ');$('versionLabel').textContent=planner.mode==='simple'?'Is there homework? Check Yes or No for each subject.':'Write each day’s homework and check Done when finished.';}
function printText(value,cls=''){const el=document.createElement('span');el.className='print-only '+cls;el.textContent=value;return el;}
function render(){
 heading();$('head').replaceChildren();$('body').replaceChildren();const shownDays=planner.layout==='day'?[planner.day]:Array.from({length:planner.weekends?7:5},(_,i)=>i);$('planner').classList.toggle('single-day',planner.layout==='day');$('day').hidden=$('dayLabel').hidden=planner.layout!=='day';$('weekendsLabel').hidden=planner.layout==='day';
 const row=document.createElement('tr'),subjectHead=document.createElement('th');subjectHead.textContent='Subject';subjectHead.scope='col';subjectHead.className='subject-cell';row.append(subjectHead);
 for(const day of shownDays){const th=document.createElement('th');th.scope='col';th.textContent=HomeworkData.days[day];row.append(th);}$('head').append(row);
 planner.subjects.forEach((subject,index)=>{const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';const input=document.createElement('input');input.type='text';input.maxLength=60;input.value=subject.name;input.setAttribute('aria-label',`Subject ${index+1}`);input.onchange=()=>{subject.name=input.value;render();};const remove=document.createElement('button');remove.textContent='Remove subject';remove.className='no-print';remove.disabled=planner.subjects.length===1;remove.onclick=()=>{planner.subjects.splice(index,1);render();};th.append(input,printText(subject.name));if(subject.pictogramId||subject.image){const img=document.createElement('img');img.src=subject.pictogramId?ARASAAC.imageUrl(subject.pictogramId):subject.image;img.alt=subject.name;img.className='subject-image';th.append(img);}const choose=document.createElement('button');choose.type='button';choose.className='no-print';choose.textContent='Choose picture';choose.setAttribute('aria-label',`Choose picture for ${subject.name||'subject'}`);choose.onclick=()=>openPicker(subject);th.append(choose);th.append(remove);tr.append(th);
  for(const day of shownDays){const e=subject.entries[day],td=document.createElement('td'),context=`${subject.name||`Subject ${index+1}`} on ${HomeworkData.days[day]}`;
   if(planner.mode==='simple'){const group=document.createElement('div');group.className='homework-answers';group.setAttribute('role','group');group.setAttribute('aria-label',`Homework: ${context}`);for(const value of ['yes','no']){const button=document.createElement('button');button.type='button';button.className=`homework-answer answer-${value}`;button.setAttribute('aria-label',`${value==='yes'?'Yes':'No'} homework: ${context}`);button.setAttribute('aria-pressed',String(e.homework===value));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',value==='yes'?'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z':'M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm5 13.59L15.59 17 12 13.41 8.41 17 7 15.59 10.59 12 7 8.41 8.41 7 12 10.59 15.59 7 17 8.41 13.41 12 17 15.59z');svg.append(path);const label=document.createElement('span');label.textContent=value==='yes'?'Yes':'No';button.append(svg,label);button.onclick=()=>{e.homework=e.homework===value?'':value;for(const choice of group.children)choice.setAttribute('aria-pressed',String(choice===button&&e.homework===value));};group.append(button);}td.append(group);}

   else{const text=document.createElement('textarea');text.maxLength=500;text.value=e.assignment;text.setAttribute('aria-label',`Homework: ${context}`);const printed=printText(e.assignment,'assignment-print');text.oninput=()=>{e.assignment=text.value;printed.textContent=e.assignment;};const label=document.createElement('label'),done=document.createElement('input');done.type='checkbox';done.checked=e.done;done.setAttribute('aria-label',`Done: ${context}`);done.onchange=()=>{e.done=done.checked;td.classList.toggle('homework-done',e.done);};td.classList.toggle('homework-done',e.done);label.append(done,' Done');td.append(text,printed,label);}tr.append(td);
  }$('body').append(tr);
 });$('addSubject').disabled=planner.subjects.length>=8;
}
function sync(){for(const field of ['title','person','week','mode','layout','day'])$(field).value=planner[field];$('weekends').checked=planner.weekends;render();}
for(const field of ['title','person','week'])$(field).oninput=()=>{planner[field]=$(field).value;heading();};$('mode').onchange=()=>{planner.mode=$('mode').value;render();};$('weekends').onchange=()=>{planner.weekends=$('weekends').checked;render();};$('addSubject').onclick=()=>{if(planner.subjects.length<8){planner.subjects.push(HomeworkData.subject('New subject'));render();}};
$('layout').onchange=()=>{planner.layout=$('layout').value;render();};$('day').onchange=()=>{planner.day=Number($('day').value);render();};HomeworkData.days.forEach((name,index)=>$('day').append(new Option(name,index)));
const picker=$('iconPicker');let pickerSubject=null,searchRevision=0;
function openPicker(subject){pickerSubject=subject;$('iconSearch').value=subject.name;picker.showModal();searchPictures();}
async function searchPictures(){const revision=++searchRevision,term=$('iconSearch').value.trim();$('iconResults').replaceChildren();if(!term){$('iconStatus').textContent='Enter a word to find a picture.';return;}$('iconStatus').textContent='Searching ARASAAC…';const matches=await ARASAAC.search(term);if(revision!==searchRevision||!picker.open)return;$('iconStatus').textContent=matches.length?'Select a picture below.':'No pictures found. Try another word or check your connection.';matches.filter(m=>Number.isSafeInteger(m._id)&&m._id>0).slice(0,30).forEach(match=>{const button=document.createElement('button');button.type='button';button.className='icon-choice';const label=match.keywords?.[0]?.keyword||`Symbol ${match._id}`;button.setAttribute('aria-label',`Use ${label} picture`);const image=document.createElement('img');image.src=ARASAAC.imageUrl(match._id);image.alt='';const caption=document.createElement('span');caption.textContent=label;button.append(image,caption);button.onclick=()=>{if(planner.subjects.includes(pickerSubject)){pickerSubject.pictogramId=match._id;pickerSubject.image='';render();say('ARASAAC picture selected. Save board to keep it.');}picker.close();};$('iconResults').append(button);});}
$('iconSearchForm').onsubmit=event=>{event.preventDefault();searchPictures();};$('closePicker').onclick=()=>picker.close();$('removeIcon').onclick=()=>{if(planner.subjects.includes(pickerSubject)){pickerSubject.pictogramId=null;pickerSubject.image='';render();}picker.close();};picker.addEventListener('close',()=>{pickerSubject=null;searchRevision++;});
function currentPayload(){return HomeworkData.serialize(planner);}
function library(){const saved=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(saved))throw Error('Saved planners could not be read.');saved.forEach(entry=>{if(typeof entry.id!=='string')throw Error('Invalid saved planner.');HomeworkData.validate(entry.payload);});return saved;}
function refresh(){$('savedBoards').replaceChildren(new Option('Choose a saved planner',''));try{library().forEach(entry=>$('savedBoards').append(new Option(entry.payload.board.title,entry.id)));$('savedBoards').value=savedId||'';}catch(e){say(e.message);}}
$('saveBoard').onclick=()=>{try{if(!planner.title.trim())throw Error('Give your planner a name.');const saved=library(),id=savedId||crypto.randomUUID(),entry={id,payload:currentPayload()},index=saved.findIndex(item=>item.id===id);if(index<0)saved.push(entry);else saved[index]=entry;localStorage.setItem(key,JSON.stringify(saved));savedId=id;refresh();say('Planner saved in this browser.');}catch(e){say(`Could not save: ${e.message}`);}};
$('loadBoard').onclick=()=>{try{const entry=library().find(item=>item.id===$('savedBoards').value);if(!entry)throw Error('Choose a saved planner first.');planner=HomeworkData.validate(entry.payload);savedId=entry.id;sync();say('Planner loaded.');}catch(e){say(e.message);}};
$('deleteBoard').onclick=()=>{try{const saved=library(),entry=saved.find(item=>item.id===$('savedBoards').value);if(!entry)throw Error('Choose a saved planner first.');if(!confirm(`Delete the saved copy of “${entry.payload.board.title}”? The open planner stays on screen.`))return;localStorage.setItem(key,JSON.stringify(saved.filter(item=>item.id!==entry.id)));if(savedId===entry.id)savedId=null;refresh();say('Saved copy deleted.');}catch(e){say(e.message);}};
$('exportBoard').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(currentPayload(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`homework-${planner.title.replace(/[^a-z0-9_-]+/gi,'-')||'planner'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importBoard').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{const file=$('importFile').files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('Choose a file smaller than 5 MB.');const validated=HomeworkData.validate(JSON.parse(await file.text()));planner=validated;savedId=null;sync();refresh();say('Imported. Save board to keep this planner in your browser.');}catch(e){say(`Could not import: ${e.message} Your planner is unchanged.`);}finally{$('importFile').value='';}};
$('printBoard').onclick=()=>window.print();sync();refresh();
